title: DaruMeik's Blog
description: Random CG-related stuffs translated for Vietnamese dev.

remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark

nav_pages:
  - _pages/about.md
  - _pages/translation.md